import mods.jei.ingredient

//Replace rftools quarry and pump with buildcraft
mods.jei.ingredient.removeAndHide(item('rftools:shape_card', 2))
mods.jei.ingredient.removeAndHide(item('rftools:shape_card', 3))
mods.jei.ingredient.removeAndHide(item('rftools:shape_card', 4))
mods.jei.ingredient.removeAndHide(item('rftools:shape_card', 5))
mods.jei.ingredient.removeAndHide(item('rftools:shape_card', 6))
mods.jei.ingredient.removeAndHide(item('rftools:shape_card', 7))
mods.jei.ingredient.removeAndHide(item('rftools:shape_card', 8))
mods.jei.ingredient.removeAndHide(item('rftools:shape_card', 9))
mods.jei.ingredient.removeAndHide(item('rftools:shape_card', 10))
crafting.removeByOutput(item('buildcraftbuilders:quarry'), false)
crafting.addShaped('quarry', item('buildcraftbuilders:quarry'),
	[[item('thermalfoundation:material', 256),item('thermalinnovation:drill', 4),item('thermalfoundation:material', 256)],
	 [item('thermalfoundation:material', 24),item('thermalexpansion:frame'),item('thermalfoundation:material', 24)],
	 [item('thermalfoundation:material', 25),item('thermalfoundation:material', 513),item('thermalfoundation:material', 25)]])
crafting.addShaped('pump', item('buildcraftfactory:pump'),
	[[item('minecraft:iron_ingot'),item('minecraft:bucket'),item('minecraft:iron_ingot')],
	 [item('minecraft:iron_ingot'),item('thermalexpansion:frame'),item('minecraft:iron_ingot')],
	 [item('thermalexpansion:tank'),item('thermalfoundation:material', 513),item('thermalexpansion:tank')]])
crafting.addShaped('floodGate', item('buildcraftfactory:flood_gate'),
	[[item('minecraft:iron_ingot'),item('thermalexpansion:tank'),item('minecraft:iron_ingot')],
	 [item('minecraft:iron_ingot'),item('thermalexpansion:frame'),item('minecraft:iron_ingot')],
	 [item('minecraft:bucket'),item('thermalfoundation:material', 513),item('minecraft:bucket')]])
crafting.addShaped('markerConnector', item('buildcraftcore:marker_connector'),
	[[null,item('minecraft:dye', 4)],
	 [item('thermalfoundation:wrench'),null]])

mods.jei.ingredient.hide(item('buildcraftcore:spring:*'))
mods.jei.ingredient.hide(item('buildcraftcore:volume_box'))
mods.jei.ingredient.hide(item('buildcraftbuilders:frame'))
mods.jei.ingredient.hide(item('buildcraftlib:guide'))
mods.jei.ingredient.hide(item('buildcraftlib:guide').withNbt(['BookName': 'buildcraftlib:meta']))
mods.jei.ingredient.hide(item('buildcraftlib:guide_note'))
mods.jei.ingredient.hide(item('buildcraftlib:debugger'))
mods.jei.ingredient.hide(fluid('oil_heat_1'))
mods.jei.ingredient.hide(fluid('oil_heat_2'))
mods.jei.ingredient.hide(fluid('oil_dense'))
mods.jei.ingredient.hide(fluid('oil_dense_heat_1'))
mods.jei.ingredient.hide(fluid('oil_dense_heat_2'))
mods.jei.ingredient.hide(fluid('oil_distilled'))
mods.jei.ingredient.hide(fluid('oil_distilled_heat_1'))
mods.jei.ingredient.hide(fluid('oil_distilled_heat_2'))
mods.jei.ingredient.hide(fluid('oil_heavy'))
mods.jei.ingredient.hide(fluid('oil_heavy_heat_1'))
mods.jei.ingredient.hide(fluid('oil_heavy_heat_2'))
mods.jei.ingredient.hide(fluid('oil_residue'))
mods.jei.ingredient.hide(fluid('oil_residue_heat_1'))
mods.jei.ingredient.hide(fluid('oil_residue_heat_2'))
mods.jei.ingredient.hide(fluid('fuel_dense'))
mods.jei.ingredient.hide(fluid('fuel_dense_heat_1'))
mods.jei.ingredient.hide(fluid('fuel_dense_heat_2'))
mods.jei.ingredient.hide(fluid('fuel_mixed_heavy'))
mods.jei.ingredient.hide(fluid('fuel_mixed_heavy_heat_1'))
mods.jei.ingredient.hide(fluid('fuel_mixed_heavy_heat_2'))
mods.jei.ingredient.hide(fluid('fuel_light'))
mods.jei.ingredient.hide(fluid('fuel_light_heat_1'))
mods.jei.ingredient.hide(fluid('fuel_light_heat_2'))
mods.jei.ingredient.hide(fluid('fuel_mixed_light'))
mods.jei.ingredient.hide(fluid('fuel_mixed_light_heat_1'))
mods.jei.ingredient.hide(fluid('fuel_mixed_light_heat_2'))
mods.jei.ingredient.hide(fluid('fuel_gaseous'))
mods.jei.ingredient.hide(fluid('fuel_gaseous_heat_1'))
mods.jei.ingredient.hide(fluid('fuel_gaseous_heat_2'))
mods.jei.ingredient.hide(item('forge:bucketfilled').withNbt(['FluidName': 'oil_heat_1', 'Amount': 1000]))
mods.jei.ingredient.hide(item('forge:bucketfilled').withNbt(['FluidName': 'oil_heat_2', 'Amount': 1000]))
mods.jei.ingredient.hide(item('forge:bucketfilled').withNbt(['FluidName': 'oil_dense', 'Amount': 1000]))
mods.jei.ingredient.hide(item('forge:bucketfilled').withNbt(['FluidName': 'oil_dense_heat_1', 'Amount': 1000]))
mods.jei.ingredient.hide(item('forge:bucketfilled').withNbt(['FluidName': 'oil_dense_heat_2', 'Amount': 1000]))
mods.jei.ingredient.hide(item('forge:bucketfilled').withNbt(['FluidName': 'oil_distilled', 'Amount': 1000]))
mods.jei.ingredient.hide(item('forge:bucketfilled').withNbt(['FluidName': 'oil_distilled_heat_1', 'Amount': 1000]))
mods.jei.ingredient.hide(item('forge:bucketfilled').withNbt(['FluidName': 'oil_distilled_heat_2', 'Amount': 1000]))
mods.jei.ingredient.hide(item('forge:bucketfilled').withNbt(['FluidName': 'oil_heavy', 'Amount': 1000]))
mods.jei.ingredient.hide(item('forge:bucketfilled').withNbt(['FluidName': 'oil_heavy_heat_1', 'Amount': 1000]))
mods.jei.ingredient.hide(item('forge:bucketfilled').withNbt(['FluidName': 'oil_heavy_heat_2', 'Amount': 1000]))
mods.jei.ingredient.hide(item('forge:bucketfilled').withNbt(['FluidName': 'oil_residue', 'Amount': 1000]))
mods.jei.ingredient.hide(item('forge:bucketfilled').withNbt(['FluidName': 'oil_residue_heat_1', 'Amount': 1000]))
mods.jei.ingredient.hide(item('forge:bucketfilled').withNbt(['FluidName': 'oil_residue_heat_2', 'Amount': 1000]))
mods.jei.ingredient.hide(item('forge:bucketfilled').withNbt(['FluidName': 'fuel_dense', 'Amount': 1000]))
mods.jei.ingredient.hide(item('forge:bucketfilled').withNbt(['FluidName': 'fuel_dense_heat_1', 'Amount': 1000]))
mods.jei.ingredient.hide(item('forge:bucketfilled').withNbt(['FluidName': 'fuel_dense_heat_2', 'Amount': 1000]))
mods.jei.ingredient.hide(item('forge:bucketfilled').withNbt(['FluidName': 'fuel_mixed_heavy', 'Amount': 1000]))
mods.jei.ingredient.hide(item('forge:bucketfilled').withNbt(['FluidName': 'fuel_mixed_heavy_heat_1', 'Amount': 1000]))
mods.jei.ingredient.hide(item('forge:bucketfilled').withNbt(['FluidName': 'fuel_mixed_heavy_heat_2', 'Amount': 1000]))
mods.jei.ingredient.hide(item('forge:bucketfilled').withNbt(['FluidName': 'fuel_light', 'Amount': 1000]))
mods.jei.ingredient.hide(item('forge:bucketfilled').withNbt(['FluidName': 'fuel_light_heat_1', 'Amount': 1000]))
mods.jei.ingredient.hide(item('forge:bucketfilled').withNbt(['FluidName': 'fuel_light_heat_2', 'Amount': 1000]))
mods.jei.ingredient.hide(item('forge:bucketfilled').withNbt(['FluidName': 'fuel_mixed_light', 'Amount': 1000]))
mods.jei.ingredient.hide(item('forge:bucketfilled').withNbt(['FluidName': 'fuel_mixed_light_heat_1', 'Amount': 1000]))
mods.jei.ingredient.hide(item('forge:bucketfilled').withNbt(['FluidName': 'fuel_mixed_light_heat_2', 'Amount': 1000]))
mods.jei.ingredient.hide(item('forge:bucketfilled').withNbt(['FluidName': 'fuel_gaseous', 'Amount': 1000]))
mods.jei.ingredient.hide(item('forge:bucketfilled').withNbt(['FluidName': 'fuel_gaseous_heat_1', 'Amount': 1000]))
mods.jei.ingredient.hide(item('forge:bucketfilled').withNbt(['FluidName': 'fuel_gaseous_heat_2', 'Amount': 1000]));