//NO_RUN
import loottweaker.LootTweaker
import loottweaker.vanilla.loot.LootTable
import loottweaker.vanilla.loot.LootPool
import crafttweaker.data.IData

//Loot tables
def desert = LootTweaker.getTable('minecraft:chests/desert_pyramid')
def desert_pool = desert.getPool('main')
def nether = LootTweaker.getTable('minecraft:chests/nether_bridge')
def nether_pool = nether.getPool('main')
def library = LootTweaker.getTable('minecraft:chests/stronghold_library')
def library_pool = library.getPool('main')
def mineshaft = LootTweaker.getTable('minecraft:chests/abandoned_mineshaft')
def mineshaft_pool = mineshaft.getPool('main')
def jungle = LootTweaker.getTable('minecraft:chests/jungle_temple')
def jungle_pool = jungle.getPool('main')
def dungeon = LootTweaker.getTable('minecraft:chests/simple_dungeon')
def dungeon_pool = dungeon.getPool('main')
def end = LootTweaker.getTable('minecraft:chests/end_city_treasure')
def end_pool = end.getPool('main')
def corridor = LootTweaker.getTable('minecraft:chests/stronghold_corridor')
def corridor_pool = corridor.getPool('main')
def crossing = LootTweaker.getTable('minecraft:chests/stronghold_crossing')
def crossing_pool = crossing.getPool('main')
def blacksmith = LootTweaker.getTable('minecraft:chests/village_blacksmith')
def blacksmith_pool = blacksmith.getPool('main')
def mansion = LootTweaker.getTable('minecraft:chests/woodland_mansion')
def mansion_pool = mansion.getPool('main')

//Remove enchanting
mods.jei.JEI.removeAndHide(item('minecraft:enchanting_table'))
mods.jei.JEI.removeAndHide(item('atum:disenchanting_scroll'))
mods.jei.JEI.removeAndHide(item('stevescarts:cartmodule', 82))
crafting.removeByOutput(item('rftoolsdim:efficiency_essence'))
crafting.addShaped('efficiencyEssence', item('rftoolsdim:efficiency_essence'),
	[[null,item('thermalfoundation:tool.pickaxe_platinum'),null],
	 [item('minecraft:ender_eye'),item('minecraft:nether_star'),item('minecraft:ender_eye')],
	 [null,item('minecraft:ender_eye'),null]])
crafting.removeByOutput(item('rftoolsdim:mediocre_efficiency_essence'), false)
crafting.addShaped('mediocreEfficiencyEssence', item('rftoolsdim:mediocre_efficiency_essence'),
	[[null,item('midnight:tenebrum_pickaxe'),null],
	 [item('minecraft:ender_eye'),item('minecraft:ghast_tear'),item('minecraft:ender_eye')],
	 [null,item('minecraft:ender_eye'),null]])
	 
crafting.removeByOutput(item('stevescarts:upgrade', 2), false)
crafting.addShaped('moduleKnowledge', item('stevescarts:upgrade', 2),
	[[item('minecraft:book'),item('minecraft:bookshelf'),item('minecraft:book')],
	 [item('minecraft:bookshelf'),item('minecraft:experience_bottle'),item('minecraft:bookshelf')],
	 [item('stevescarts:modulecomponents', 22),item('stevescarts:modulecomponents', 59),item('stevescarts:modulecomponents', 22)]])
	 
crafting.removeByOutput(item('stevescarts:upgrade', 4), false)
crafting.addShaped('upgradeExperiencedAssembler', item('stevescarts:upgrade', 4),
	[[null,item('minecraft:experience_bottle'),null],
	 [null,item('minecraft:redstone'),null],
	 [item('minecraft:iron_ingot'),item('stevescarts:modulecomponents', 59),item('minecraft:iron_ingot')]])
	 
crafting.removeByOutput(item('stevescarts:upgrade', 5), false)
crafting.addShaped('upgradeNewEra', item('stevescarts:upgrade', 5),
	[[item('stevescarts:modulecomponents', 47),item('minecraft:experience_bottle'),item('stevescarts:modulecomponents', 47)],
	 [item('stevescarts:modulecomponents', 47),item('stevescarts:modulecomponents', 16),item('stevescarts:modulecomponents', 47)],
	 [item('stevescarts:modulecomponents', 47),item('stevescarts:upgrade', 4),item('stevescarts:modulecomponents', 47)]])

mods.jei.JEI.removeAndHide(item('refinedstorage:upgrade', 6))
mods.jei.JEI.removeAndHide(item('refinedstorage:upgrade', 7))
mods.jei.JEI.removeAndHide(item('refinedstorage:upgrade', 8))
mods.jei.JEI.removeAndHide(item('refinedstorage:upgrade', 9))

desert_pool.removeEntry('minecraft:book')
library_pool.removeEntry('minecraft:book#0')
jungle_pool.removeEntry('minecraft:book')
dungeon_pool.removeEntry('minecraft:book')
corridor_pool.removeEntry('minecraft:book')
crossing_pool.removeEntry('minecraft:book')
library_pool.removeEntry('minecraft:book')
mansion_pool.removeEntry('minecraft:book')
mineshaft_pool.removeEntry('minecraft:book')

mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 1 'as' 'short', 'id': 0 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 2 'as' 'short', 'id': 0 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 3 'as' 'short', 'id': 0 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 4 'as' 'short', 'id': 0 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 1 'as' 'short', 'id': 1 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 2 'as' 'short', 'id': 1 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 3 'as' 'short', 'id': 1 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 4 'as' 'short', 'id': 1 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 1 'as' 'short', 'id': 2 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 2 'as' 'short', 'id': 2 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 3 'as' 'short', 'id': 2 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 4 'as' 'short', 'id': 2 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 1 'as' 'short', 'id': 3 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 2 'as' 'short', 'id': 3 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 3 'as' 'short', 'id': 3 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 4 'as' 'short', 'id': 3 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 1 'as' 'short', 'id': 4 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 2 'as' 'short', 'id': 4 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 3 'as' 'short', 'id': 4 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 4 'as' 'short', 'id': 4 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 1 'as' 'short', 'id': 5 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 2 'as' 'short', 'id': 5 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 3 'as' 'short', 'id': 5 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 1 'as' 'short', 'id': 6 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 1 'as' 'short', 'id': 7 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 2 'as' 'short', 'id': 7 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 3 'as' 'short', 'id': 7 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 1 'as' 'short', 'id': 8 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 2 'as' 'short', 'id': 8 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 3 'as' 'short', 'id': 8 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 1 'as' 'short', 'id': 9 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 2 'as' 'short', 'id': 9 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 1 'as' 'short', 'id': 10 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 1 'as' 'short', 'id': 16 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 2 'as' 'short', 'id': 16 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 3 'as' 'short', 'id': 16 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 4 'as' 'short', 'id': 16 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 5 'as' 'short', 'id': 16 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 1 'as' 'short', 'id': 17 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 2 'as' 'short', 'id': 17 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 3 'as' 'short', 'id': 17 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 4 'as' 'short', 'id': 17 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 5 'as' 'short', 'id': 17 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 1 'as' 'short', 'id': 18 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 2 'as' 'short', 'id': 18 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 3 'as' 'short', 'id': 18 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 4 'as' 'short', 'id': 18 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 5 'as' 'short', 'id': 18 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 1 'as' 'short', 'id': 19 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 2 'as' 'short', 'id': 19 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 1 'as' 'short', 'id': 20 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 2 'as' 'short', 'id': 20 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 1 'as' 'short', 'id': 21 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 2 'as' 'short', 'id': 21 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 3 'as' 'short', 'id': 21 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 1 'as' 'short', 'id': 22 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 2 'as' 'short', 'id': 22 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 3 'as' 'short', 'id': 22 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 1 'as' 'short', 'id': 32 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 2 'as' 'short', 'id': 32 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 3 'as' 'short', 'id': 32 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 4 'as' 'short', 'id': 32 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 5 'as' 'short', 'id': 32 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 1 'as' 'short', 'id': 33 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 1 'as' 'short', 'id': 34 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 2 'as' 'short', 'id': 34 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 3 'as' 'short', 'id': 34 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 1 'as' 'short', 'id': 35 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 2 'as' 'short', 'id': 35 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 3 'as' 'short', 'id': 35 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 1 'as' 'short', 'id': 48 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 2 'as' 'short', 'id': 48 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 3 'as' 'short', 'id': 48 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 4 'as' 'short', 'id': 48 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 5 'as' 'short', 'id': 48 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 1 'as' 'short', 'id': 49 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 2 'as' 'short', 'id': 49 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 1 'as' 'short', 'id': 50 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 1 'as' 'short', 'id': 51 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 1 'as' 'short', 'id': 61 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 2 'as' 'short', 'id': 61 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 3 'as' 'short', 'id': 61 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 1 'as' 'short', 'id': 62 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 2 'as' 'short', 'id': 62 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 3 'as' 'short', 'id': 62 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 1 'as' 'short', 'id': 70 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 1 'as' 'short', 'id': 71 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 1 'as' 'short', 'id': 11 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 1 'as' 'short', 'id': 12 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 2 'as' 'short', 'id': 12 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 3 'as' 'short', 'id': 12 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 4 'as' 'short', 'id': 12 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 1 'as' 'short', 'id': 13 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 2 'as' 'short', 'id': 13 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 2 'as' 'short', 'id': 13 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 3 'as' 'short', 'id': 13 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 1 'as' 'short', 'id': 14 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 2 'as' 'short', 'id': 14 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 3 'as' 'short', 'id': 14 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 4 'as' 'short', 'id': 14 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 1 'as' 'short', 'id': 15 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 2 'as' 'short', 'id': 15 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 3 'as' 'short', 'id': 15 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 4 'as' 'short', 'id': 15 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 1 'as' 'short', 'id': 23 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 1 'as' 'short', 'id': 24 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 1 'as' 'short', 'id': 25 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 2 'as' 'short', 'id': 25 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 3 'as' 'short', 'id': 25 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 1 'as' 'short', 'id': 26 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 2 'as' 'short', 'id': 26 'as' 'short']]]))
mods.jei.JEI.removeAndHide(item('minecraft:enchanted_book').withNbt(['StoredEnchantments': [['lvl': 3 'as' 'short', 'id': 26 'as' 'short']]]));