//NO_RUN
import loottweaker.LootTweaker
import loottweaker.vanilla.loot.LootTable
import loottweaker.vanilla.loot.LootPool
import crafttweaker.data.IData

//Loot tables
def desert = LootTweaker.getTable('minecraft:chests/desert_pyramid').getPool('main')
def nether = LootTweaker.getTable('minecraft:chests/nether_bridge').getPool('main')
def jungle = LootTweaker.getTable('minecraft:chests/jungle_temple').getPool('main')
def dungeon = LootTweaker.getTable('minecraft:chests/simple_dungeon').getPool('main')
def end = LootTweaker.getTable('minecraft:chests/end_city_treasure').getPool('main')
def blacksmith = LootTweaker.getTable('minecraft:chests/village_blacksmith').getPool('main')
def mansion = LootTweaker.getTable('minecraft:chests/woodland_mansion').getPool('main')
def corridor = LootTweaker.getTable('minecraft:chests/stronghold_corridor').getPool('main')

//Remove gemstone tools and armour
mods.jei.JEI.removeAndHide(item('projectred-exploration:ruby_axe'))
mods.jei.JEI.removeAndHide(item('projectred-exploration:ruby_hoe'))
mods.jei.JEI.removeAndHide(item('projectred-exploration:ruby_pickaxe'))
mods.jei.JEI.removeAndHide(item('projectred-exploration:ruby_shovel'))
mods.jei.JEI.removeAndHide(item('projectred-exploration:ruby_sword'))
mods.jei.JEI.removeAndHide(item('projectred-exploration:ruby_saw'))
mods.jei.JEI.removeAndHide(item('projectred-exploration:ruby_sickle'))
mods.jei.JEI.removeAndHide(item('projectred-exploration:ruby_helmet'))
mods.jei.JEI.removeAndHide(item('projectred-exploration:ruby_chestplate'))
mods.jei.JEI.removeAndHide(item('projectred-exploration:ruby_leggings'))
mods.jei.JEI.removeAndHide(item('projectred-exploration:ruby_boots'))
mods.jei.JEI.removeAndHide(item('projectred-exploration:sapphire_axe'))
mods.jei.JEI.removeAndHide(item('projectred-exploration:sapphire_hoe'))
mods.jei.JEI.removeAndHide(item('projectred-exploration:sapphire_pickaxe'))
mods.jei.JEI.removeAndHide(item('projectred-exploration:sapphire_shovel'))
mods.jei.JEI.removeAndHide(item('projectred-exploration:sapphire_sword'))
mods.jei.JEI.removeAndHide(item('projectred-exploration:sapphire_saw'))
mods.jei.JEI.removeAndHide(item('projectred-exploration:sapphire_sickle'))
mods.jei.JEI.removeAndHide(item('projectred-exploration:sapphire_helmet'))
mods.jei.JEI.removeAndHide(item('projectred-exploration:sapphire_chestplate'))
mods.jei.JEI.removeAndHide(item('projectred-exploration:sapphire_leggings'))
mods.jei.JEI.removeAndHide(item('projectred-exploration:sapphire_boots'))
mods.jei.JEI.removeAndHide(item('projectred-exploration:peridot_axe'))
mods.jei.JEI.removeAndHide(item('projectred-exploration:peridot_hoe'))
mods.jei.JEI.removeAndHide(item('projectred-exploration:peridot_pickaxe'))
mods.jei.JEI.removeAndHide(item('projectred-exploration:peridot_shovel'))
mods.jei.JEI.removeAndHide(item('projectred-exploration:peridot_sword'))
mods.jei.JEI.removeAndHide(item('projectred-exploration:peridot_saw'))
mods.jei.JEI.removeAndHide(item('projectred-exploration:peridot_sickle'))
mods.jei.JEI.removeAndHide(item('projectred-exploration:peridot_helmet'))
mods.jei.JEI.removeAndHide(item('projectred-exploration:peridot_chestplate'))
mods.jei.JEI.removeAndHide(item('projectred-exploration:peridot_leggings'))
mods.jei.JEI.removeAndHide(item('projectred-exploration:peridot_boots'))
mods.jei.JEI.removeAndHide(item('minecraft:diamond_axe'))
mods.jei.JEI.removeAndHide(item('minecraft:diamond_hoe'))
mods.jei.JEI.removeAndHide(item('minecraft:diamond_pickaxe'))
mods.jei.JEI.removeAndHide(item('minecraft:diamond_shovel'))
mods.jei.JEI.removeAndHide(item('minecraft:diamond_sword'))
mods.jei.JEI.removeAndHide(item('microblockcbe:saw_diamond'))
mods.jei.JEI.removeAndHide(item('projectred-exploration:diamond_sickle'))
mods.jei.JEI.removeAndHide(item('thermalfoundation:tool.bow_diamond'))
mods.jei.JEI.removeAndHide(item('thermalfoundation:tool.fishing_rod_diamond'))
mods.jei.JEI.removeAndHide(item('thermalfoundation:tool.shears_diamond'))
mods.jei.JEI.removeAndHide(item('thermalfoundation:tool.sickle_diamond'))
mods.jei.JEI.removeAndHide(item('thermalfoundation:tool.hammer_diamond'))
mods.jei.JEI.removeAndHide(item('thermalfoundation:tool.excavator_diamond'))
mods.jei.JEI.removeAndHide(item('thermalfoundation:tool.shield_diamond'))
mods.jei.JEI.removeAndHide(item('thermalfoundation:material', 16))
mods.jei.JEI.removeAndHide(item('thermalfoundation:material', 26))
mods.jei.JEI.removeAndHide(item('minecraft:diamond_helmet'))
mods.jei.JEI.removeAndHide(item('minecraft:diamond_chestplate'))
mods.jei.JEI.removeAndHide(item('minecraft:diamond_leggings'))
mods.jei.JEI.removeAndHide(item('minecraft:diamond_boots'))
mods.jei.JEI.removeAndHide(item('minecraft:diamond_horse_armor'))
crafting.removeByOutput(item('atum:desert_helmet_diamond'), false)
crafting.removeByOutput(item('atum:desert_chest_diamond'), false)
crafting.removeByOutput(item('atum:desert_legs_diamond'), false)
crafting.removeByOutput(item('atum:desert_boots_diamond'), false)
crafting.addShapeless('desertHelmetPlatinum', item('atum:desert_helmet_diamond'), [item('atum:wanderer_helmet'),item('thermalfoundation:armor.helmet_platinum')])
crafting.addShapeless('desertChestPlatinum', item('atum:desert_chest_diamond'), [item('atum:wanderer_chest'),item('thermalfoundation:armor.plate_platinum')])
crafting.addShapeless('desertLegsPlatinum', item('atum:desert_legs_diamond'), [item('atum:wanderer_legs'),item('thermalfoundation:armor.legs_platinum')])
crafting.addShapeless('desertBootsPlatinum', item('atum:desert_boots_diamond'), [item('atum:wanderer_boots'),item('thermalfoundation:armor.boots_platinum')])
crafting.removeByOutput(item('thermalexpansion:augment', 416), false)
crafting.addShaped('enstabulationApparatus', item('thermalexpansion:augment', 416),
	[[null,item('thermalfoundation:material', 290),null],
	 [item('thermalfoundation:tool.sword_invar'),item('thermalfoundation:material', 512),item('thermalfoundation:tool.sword_invar')],
	 [null,item('minecraft:piston'),null]])
crafting.removeByOutput(item('rftools:haste_module'))
crafting.addShaped('hasteModule', item('rftools:haste_module'),
	[[null,item('midnight:tenebrum_pickaxe'),null],
	 [item('minecraft:redstone'),item('minecraft:gold_ingot'),item('minecraft:redstone')],
	 [null,item('minecraft:dye', 0),null]])
crafting.removeByOutput(item('rftools:hasteplus_module'))
crafting.addShapeless('hastePlusModule', item('rftools:hasteplus_module'), [item('rftools:haste_module'), item('thermalfoundation:tool.pickaxe_platinum')])
end.removeEntry('minecraft:diamond_horse_armor')
end.removeEntry('minecraft:diamond_helmet')
end.removeEntry('minecraft:diamond_chestplate')
end.removeEntry('minecraft:diamond_leggings')
end.removeEntry('minecraft:diamond_boots')
end.removeEntry('minecraft:diamond_pickaxe')
end.removeEntry('minecraft:diamond_shovel')
end.removeEntry('minecraft:diamond_sword')
end.addItemEntry(item('thermalfoundation:horse_armor_platinum'), 1)
end.addItemEntry(item('thermalfoundation:material', 134), 5)
dungeon.removeEntry('minecraft:diamond_horse_armor')
dungeon.addItemEntry(item('thermalfoundation:horse_armor_platinum'), 5)
blacksmith.removeEntry('minecraft:diamond_horse_armor')
blacksmith.addItemEntry(item('thermalfoundation:horse_armor_platinum'), 1)
nether.removeEntry('minecraft:diamond_horse_armor')
nether.addItemEntry(item('thermalfoundation:horse_armor_platinum'), 3)
desert.removeEntry('minecraft:diamond_horse_armor')
desert.addItemEntry(item('thermalfoundation:horse_armor_platinum'), 5)
jungle.removeEntry('minecraft:diamond_horse_armor')
jungle.addItemEntry(item('thermalfoundation:horse_armor_platinum'), 1)
mansion.removeEntry('minecraft:diamond_chestplate')
mansion.removeEntry('minecraft:diamond_hoe')
mansion.addItemEntry(item('thermalfoundation:tool.hoe_platinum'), 15)
corridor.removeEntry('minecraft:diamond_horse_armor')
corridor.addItemEntry(item('thermalfoundation:horse_armor_platinum'), 1);