import mods.jei.ingredient

//Remove redundant items
mods.jei.ingredient.removeAndHide(item('advancedrocketry:basiclasergun'))
mods.jei.ingredient.removeAndHide(item('advancedrocketry:basalt'))
mods.jei.ingredient.removeAndHide(item('advancedrocketry:platepress'))
mods.jei.ingredient.removeAndHide(item('advancedrocketry:hovercraft'))
mods.jei.ingredient.removeAndHide(item('advancedrocketry:landingfloat'))
mods.jei.ingredient.removeAndHide(item('bigreactors:ingotsteel'))
mods.jei.ingredient.removeAndHide(item('bigreactors:duststeel'))
mods.jei.ingredient.removeAndHide(item('bigreactors:orebenitoite'))
mods.jei.ingredient.removeAndHide(item('bigreactors:oreanglesite'))
mods.jei.ingredient.removeAndHide(item('bigreactors:mineralbenitoite'))
mods.jei.ingredient.removeAndHide(item('bigreactors:mineralanglesite'))
mods.jei.ingredient.removeAndHide(item('bigreactors:ingotludicrite'))
mods.jei.ingredient.removeAndHide(item('bigreactors:dustludicrite'))
mods.jei.ingredient.removeAndHide(item('bigreactors:blockludicrite'))
mods.jei.ingredient.removeAndHide(item('projectred-core:resource_item', 2))
mods.jei.ingredient.removeAndHide(item('projectred-core:resource_item', 3))
mods.jei.ingredient.removeAndHide(item('projectred-core:resource_item', 4))
mods.jei.ingredient.removeAndHide(item('projectred-core:resource_item', 10))
mods.jei.ingredient.removeAndHide(item('projectred-core:resource_item', 12))
mods.jei.ingredient.removeAndHide(item('projectred-core:resource_item', 20))
mods.jei.ingredient.removeAndHide(item('projectred-core:resource_item', 21))
mods.jei.ingredient.removeAndHide(item('projectred-core:resource_item', 100))
mods.jei.ingredient.removeAndHide(item('projectred-core:resource_item', 101))
mods.jei.ingredient.removeAndHide(item('projectred-core:resource_item', 102))
mods.jei.ingredient.removeAndHide(item('projectred-core:resource_item', 104))
mods.jei.ingredient.removeAndHide(item('projectred-core:resource_item', 105))
mods.jei.ingredient.removeAndHide(item('projectred-core:resource_item', 200))
mods.jei.ingredient.removeAndHide(item('projectred-core:resource_item', 201))
mods.jei.ingredient.removeAndHide(item('projectred-core:resource_item', 202))
mods.jei.ingredient.removeAndHide(item('projectred-core:resource_item', 250))
mods.jei.ingredient.removeAndHide(item('projectred-core:resource_item', 252))
mods.jei.ingredient.removeAndHide(item('projectred-core:resource_item', 300))
mods.jei.ingredient.removeAndHide(item('projectred-core:resource_item', 301))
mods.jei.ingredient.removeAndHide(item('projectred-core:resource_item', 310))
mods.jei.ingredient.removeAndHide(item('projectred-core:resource_item', 311))
mods.jei.ingredient.removeAndHide(item('projectred-core:resource_item', 312))
mods.jei.ingredient.removeAndHide(item('projectred-core:resource_item', 320))
mods.jei.ingredient.removeAndHide(item('projectred-core:resource_item', 341))
mods.jei.ingredient.removeAndHide(item('projectred-core:resource_item', 342))
mods.jei.ingredient.removeAndHide(item('projectred-core:resource_item', 400))
mods.jei.ingredient.removeAndHide(item('projectred-core:resource_item', 401))
mods.jei.ingredient.removeAndHide(item('projectred-core:resource_item', 402))
mods.jei.ingredient.removeAndHide(item('projectred-core:resource_item', 410))
mods.jei.ingredient.removeAndHide(item('projectred-core:resource_item', 420))
mods.jei.ingredient.removeAndHide(item('projectred-core:resource_item', 421))
mods.jei.ingredient.removeAndHide(item('projectred-core:resource_item', 600))
mods.jei.ingredient.removeAndHide(item('projectred-core:screwdriver'))
mods.jei.ingredient.removeAndHide(item('projectred-core:drawplate'))
mods.jei.ingredient.removeAndHide(item('projectred-exploration:ore:*'))
mods.jei.ingredient.removeAndHide(item('projectred-exploration:stone', 5))
mods.jei.ingredient.removeAndHide(item('projectred-exploration:stone', 6))
mods.jei.ingredient.removeAndHide(item('projectred-exploration:stone', 7))
mods.jei.ingredient.removeAndHide(item('projectred-exploration:stone', 8))
mods.jei.ingredient.removeAndHide(item('projectred-exploration:stone', 9))
mods.jei.ingredient.removeAndHide(item('projectred-exploration:stone', 10))
mods.jei.ingredient.removeAndHide(item('projectred-exploration:stone', 11))
mods.jei.ingredient.removeAndHide(item('projectred-exploration:stone_wall', 5))
mods.jei.ingredient.removeAndHide(item('projectred-exploration:stone_wall', 6))
mods.jei.ingredient.removeAndHide(item('projectred-exploration:stone_wall', 7))
mods.jei.ingredient.removeAndHide(item('projectred-exploration:stone_wall', 11))
mods.jei.ingredient.removeAndHide(item('projectred-exploration:backpack:*'))
mods.jei.ingredient.removeAndHide(item('projectred-exploration:golden_saw'))
mods.jei.ingredient.removeAndHide(item('projectred-exploration:wool_gin'))
mods.jei.ingredient.removeAndHide(item('projectred-integration:gate:*'))
mods.jei.ingredient.removeAndHide(item('projectred-transmission:framed_wire', 34))
mods.jei.ingredient.removeAndHide(item('projectred-transmission:wire', 34))
mods.jei.ingredient.removeAndHide(item('libvulpes:ore0', 4))
mods.jei.ingredient.removeAndHide(item('libvulpes:ore0', 5))
mods.jei.ingredient.removeAndHide(item('libvulpes:ore0', 9))
mods.jei.ingredient.removeAndHide(item('libvulpes:ore0', 10))
mods.jei.ingredient.removeAndHide(item('libvulpes:productplate', 1))
mods.jei.ingredient.removeAndHide(item('libvulpes:productplate', 2))
mods.jei.ingredient.removeAndHide(item('libvulpes:productplate', 4))
mods.jei.ingredient.removeAndHide(item('libvulpes:productplate', 5))
mods.jei.ingredient.removeAndHide(item('libvulpes:productplate', 6))
mods.jei.ingredient.removeAndHide(item('libvulpes:productplate', 9))
mods.jei.ingredient.removeAndHide(item('libvulpes:productplate', 10))
mods.jei.ingredient.removeAndHide(item('libvulpes:productdust', 1))
mods.jei.ingredient.removeAndHide(item('libvulpes:productdust', 2))
mods.jei.ingredient.removeAndHide(item('libvulpes:productdust', 4))
mods.jei.ingredient.removeAndHide(item('libvulpes:productdust', 5))
mods.jei.ingredient.removeAndHide(item('libvulpes:productdust', 6))
mods.jei.ingredient.removeAndHide(item('libvulpes:productdust', 9))
mods.jei.ingredient.removeAndHide(item('libvulpes:productdust', 10))
mods.jei.ingredient.removeAndHide(item('libvulpes:productingot', 4))
mods.jei.ingredient.removeAndHide(item('libvulpes:productingot', 5))
mods.jei.ingredient.removeAndHide(item('libvulpes:productingot', 6))
mods.jei.ingredient.removeAndHide(item('libvulpes:productingot', 9))
mods.jei.ingredient.removeAndHide(item('libvulpes:productingot', 10))
mods.jei.ingredient.removeAndHide(item('libvulpes:productnugget', 4))
mods.jei.ingredient.removeAndHide(item('libvulpes:productnugget', 5))
mods.jei.ingredient.removeAndHide(item('libvulpes:productnugget', 6))
mods.jei.ingredient.removeAndHide(item('libvulpes:productnugget', 9))
mods.jei.ingredient.removeAndHide(item('libvulpes:productnugget', 10))
mods.jei.ingredient.removeAndHide(item('libvulpes:productgear', 6))
mods.jei.ingredient.removeAndHide(item('libvulpes:metal0', 4))
mods.jei.ingredient.removeAndHide(item('libvulpes:metal0', 5))
mods.jei.ingredient.removeAndHide(item('libvulpes:metal0', 6))
mods.jei.ingredient.removeAndHide(item('libvulpes:metal0', 9))
mods.jei.ingredient.removeAndHide(item('libvulpes:metal0', 10))
mods.jei.ingredient.removeAndHide(item('rftools:powercell'))
mods.jei.ingredient.removeAndHide(item('rftools:powercell_advanced'))
mods.jei.ingredient.removeAndHide(item('rftools:powercell_creative'))
mods.jei.ingredient.removeAndHide(item('rftools:powercell_simple'))
mods.jei.ingredient.removeAndHide(item('libvulpes:coalgenerator'))
mods.jei.ingredient.removeAndHide(item('rftools:storage_module_tablet'))
mods.jei.ingredient.removeAndHide(item('rftools:storage_module', 0))
mods.jei.ingredient.removeAndHide(item('rftools:storage_module', 1))
mods.jei.ingredient.removeAndHide(item('rftools:storage_module', 2))
mods.jei.ingredient.removeAndHide(item('rftools:storage_module', 6))
mods.jei.ingredient.removeAndHide(item('rftools:oredict_module'))
mods.jei.ingredient.removeAndHide(item('rftools:generic_module'))
mods.jei.ingredient.removeAndHide(item('rftools:filter_module'))
mods.jei.ingredient.removeAndHide(item('rftools:powercell_card'))
mods.jei.ingredient.removeAndHide(item('rftools:crafter1'))
mods.jei.ingredient.removeAndHide(item('rftools:crafter2'))
mods.jei.ingredient.removeAndHide(item('rftools:crafter3'))
mods.jei.ingredient.removeAndHide(item('rftools:modular_storage'))
mods.jei.ingredient.removeAndHide(item('rftools:remote_storage'))
mods.jei.ingredient.removeAndHide(item('rftools:item_filter'))
mods.jei.ingredient.removeAndHide(item('microblockcbe:microblock:*'))
mods.jei.ingredient.removeAndHide(item('microblockcbe:saw_stone'))
mods.jei.ingredient.removeAndHide(item('microblockcbe:saw_iron'))
mods.jei.ingredient.removeAndHide(item('microblockcbe:stone_rod'))
mods.jei.ingredient.removeAndHide(item('base:wrench'))
mods.jei.ingredient.removeAndHide(item('muchmorespiders:meath'))
mods.jei.ingredient.removeAndHide(item('muchmorespiders:nethermeat_h'))
mods.jei.ingredient.removeAndHide(item('muchmorespiders:meathc'))
mods.jei.ingredient.removeAndHide(item('muchmorespiders:mob_agressor'))
mods.jei.ingredient.removeAndHide(item('primitivemobs:mimic_orb'));